# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('client_status', models.CharField(choices=[('PENDING', 'pending'), ('LEAD', 'lead'), ('ACTIVE', 'active'), ('DISMISSED', 'dismissed')], default=('PENDING', 'pending'), max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('OFFICE', 'office'), ('HOME', 'home'), ('SHIPPING', 'shipping'), ('BILLING', 'billing')], default=('OFFICE', 'office'), max_length=8)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('tag', models.CharField(max_length=32)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('MOBILE', 'mobile'), ('HOME', 'home'), ('OFFICE', 'office')], default=('MOBILE', 'mobile'), max_length=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ManyToManyField(to='clients.ClientAddress'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.ManyToManyField(to='clients.EmailAddress'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.ManyToManyField(null=True, to='clients.PhoneNumber'),
        ),
    ]
