# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170302_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='addresses',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phones',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='tag',
            new_name='email_tag',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
