# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170310_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='person',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='person',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='person',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='addresses',
        ),
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.ClientAddress'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='emails',
        ),
        migrations.AddField(
            model_name='client',
            name='emails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.EmailAddress'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='phones',
        ),
        migrations.AddField(
            model_name='client',
            name='phones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.PhoneNumber'),
            preserve_default=False,
        ),
    ]
