# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20170310_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='addresses',
        ),
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(to='clients.ClientAddress'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LEAD', 'Lead'), ('ACTIVE', 'Active'), ('DISMISSED', 'Dismissed')], default=('PENDING', 'Pending'), max_length=16),
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='emails',
        ),
        migrations.AddField(
            model_name='client',
            name='emails',
            field=models.ManyToManyField(to='clients.EmailAddress'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='phones',
        ),
        migrations.AddField(
            model_name='client',
            name='phones',
            field=models.ManyToManyField(to='clients.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='address_type',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('HOME', 'Home'), ('SHIPPING', 'Shipping'), ('BILLING', 'Billing')], default=('OFFICE', 'Office'), max_length=8),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_type',
            field=models.CharField(choices=[('MOBILE', 'Mobile'), ('HOME', 'Home'), ('OFFICE', 'Office')], default=('MOBILE', 'Mobile'), max_length=6),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ManyToManyField(to='clients.Company'),
        ),
    ]
