# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20170310_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Company'),
            preserve_default=False,
        ),
    ]
